### ISSUE TITLE
jakies modele sa na glownej stronie

### ISSUE THREAD

**Issue by wernerolaf** [mini-pw/2019L-WarsztatyBadawcze#159]

**Comment by MatiFilozof** [comment]
Chciałbym sprostować – nie "jakieś modele", tylko modele o hashach 578d766e499119fbe9057e45d739663d, a83d5cf9f3c9dc688b8e1f64b2e92047 i 0b05bc74eca65d46db8228b61f7fc032. Są dobrze zdefiniowane.

**Comment by agosiewska** [comment]
Naprawione w #160 dzięki @MatiFilozof  :)
