### ISSUE TITLE
lista rzeczy do poprawy 

### ISSUE THREAD

**Issue by wernerolaf** [mini-pw/2019L-WarsztatyBadawcze#164]

**Comment by wernerolaf** [comment]
mckraqs popraw haberman audity

**Comment by wernerolaf** [comment]
pysiak w twoich auditach jest rsq zamiast r2

**Comment by wernerolaf** [comment]
k-sap w twoich auditach jest rsq zamiast r2

**Comment by wernerolaf** [comment]
airi314 w twoich auditach jest rsq zamiast r2

**Comment by DominikRafacz** [comment]
@wernerolaf proponuję, żebyś oznaczał ludzi przy pomocy "@", wtedy będą dostawali powiadomienia ;)

**Comment by hbaniecki** [comment]
@wernerolaf w Twoich 21 (słownie: dwudziestu jeden) plikach model.json pole "preprocessing" jest jednoelementową tablicą.  Usuń wszędzie nawiasy kwadratowe.

**Comment by wernerolaf** [comment]
@Adamoso 
"added_by": "Adamoso",
    "model_id": "d84db2ab57d12670ff7945760677217e",
    "task_id": "classification_married",
    "dataset_id": "kaggle_beauty"

nie ma recall

**Comment by wernerolaf** [comment]
poprawie ale te nawiasy nie maja znaczanie

**Comment by wernerolaf** [comment]
@Siemashko 
wiele twoich auditow nie ma "specificity"

**Comment by wernerolaf** [comment]
@granatb 
    "added_by": "granatb",
    "model_id": "8a02f7f9da5dd25ee0cbd3fb18460913",
    "task_id": "classification_predator",
    "dataset_id": "openml_zoo"

zrobiłeś ten sam bład co ja kiedys

**Comment by wernerolaf** [comment]
cannot open file './openml_diabetes/regression_pedi/7388a6e027f8648dbc177df228c6eed6/model.json': No such file or directory
@GoniaW

**Comment by wernerolaf** [comment]
id added_by       date library                       model_name              task_id
88 75c0b2a3b1bafc0057f3a189da02dedf  pysiakk 02-03-2019     mlr 75c0b2a3b1bafc0057f3a189da02dedf regression_vicdemand
           dataset_id    mse   rmse    mae     r2
88 openml_electricity 0.0037 0.0607 0.0468 0.7479

@pysiakk nazwa modelu zla

**Comment by wernerolaf** [comment]
openml_dermatology/classification_class/9ddf48ef73d740970fabd13a48745ee4/audit.json
@k-sap same null
