### ISSUE TITLE
Moj Pull request 

### ISSUE THREAD

**Issue by wernerolaf** [mini-pw/2019L-WarsztatyBadawcze#176]
z powodu problemow z konfliktami i bledu the merge tool bc is not available as 'bcompare' git mergetool usunulem i stworzylem od nowa cale repo czy moze moj pull request zastac rozwiazany?

**Comment by agosiewska** [comment]
Oczywiście, jeszcze się tylko upewnię, rozwiązany oznacza, że mam go zamknąć
?

**Comment by wernerolaf** [comment]
tak, pracuje teraz na skopiowanym od zera

**Comment by agosiewska** [comment]
Zamknęłam
