### ISSUE TITLE
Problemy z konfliktami

### ISSUE THREAD

**Issue by wernerolaf** [mini-pw/2019L-WarsztatyBadawcze#203]

**Comment by wernerolaf** [comment]
Pojawiły mi się takie rzeczy w moich plikach po uzyciu git krakena pomocy
<<<<<<< HEAD
=======

**Comment by agosiewska** [comment]
To normalne przy konfliktach. Można użyć dowolnego edytora i ręcznie te pliki naprawić (wybrać wersję, która ma zostać) lub użyć jakiegoś narzędzia do tego przeznaczonego. Na szczęście GitKraken ma taką opcję.
https://blog.axosoft.com/gitkraken-tips-2/
