### ISSUE TITLE
Laboratoria 1

### ISSUE THREAD

**Issue by agosiewska** [mini-pw/2019L-WarsztatyBadawcze#3]

**Comment by WojciechKretowicz** [comment]
Top Spotify Tracks of 2018

https://www.kaggle.com/nadintamer/top-spotify-tracks-of-2018

**Comment by witoldmerkel** [comment]
monks-problems-2
Michał Stawikowski, Witold Merkel
https://www.openml.org/d/334

**Comment by Pastuszka** [comment]
banknote-authentication
https://www.openml.org/d/1462

**Comment by granatb** [comment]
profb
https://www.openml.org/d/470

**Comment by hubertbaniecki** [comment]
irish
Hubert Baniecki, Mateusz Polakowski
https://www.openml.org/d/451

**Comment by wernerolaf** [comment]
bank-marketing
https://www.openml.org/d/1461

**Comment by k-sap** [comment]
humandevel
Karol Saputa
https://www.openml.org/d/528

**Comment by Adamoso** [comment]
heart_disease
Adam Rydelek, Piotr Miziński
https://www.kaggle.com/ronitf/heart-disease-uci

**Comment by pysiakk** [comment]
electricity
Karol Pysiak
https://www.openml.org/d/151

**Comment by GoniaW** [comment]
artificial-characters
Małgorzata Wachulec
https://www.openml.org/d/1459

**Comment by DominikRafacz** [comment]
chocolate-bar-ratings
Dominik Rafacz
https://www.kaggle.com/rtatman/chocolate-bar-ratings

**Comment by MatiFilozof** [comment]
auto_price
Mateusz Bąkała
https://www.openml.org/d/745

**Comment by maksymiuks** [comment]
https://www.openml.org/d/472

**Comment by airi314** [comment]
abalone
Aleksandra Wichrowska
https://www.openml.org/d/183

**Comment by lukaszbrzozowski** [comment]
fertility
Łukasz Brzozowski
https://www.openml.org/d/1473

**Comment by DominikRafacz** [comment]
edit:
habermans-survival

Dominik Rafaczhttps://archive.ics.uci.edu/ml/datasets/Haberman%27s+Survival

**Comment by Siemashko** [comment]
adult
Kacper Siemaszko
https://www.openml.org/d/1590
