### ISSUE TITLE
Pytania do pracy domowej 2

### ISSUE THREAD

**Issue by wernerolaf** [mini-pw/2019L-WarsztatyBadawcze#46]
W przykładowym model.json pokazano w parameters tylko defaultowe parametry, a nie wzieto pod uwage zmiany np. ilości drzew na 500 informacje zaś o tym można było się dowiedzieć pytając o hiperparametry. Po za tym co zrobić z session info?

**Comment by agosiewska** [comment]
Dziękuję, poprawiłam jsona.
Session info jest po to, żeby wyniki były reprodukowalne. Kilka miesięcy temu zwyszła nowa wersja biblioteki randomForest, która zmieniła domyślny seed. Przez to ten sam kod dla różnych wersji tej biblioteki generował różne modele. 
Mając session info posiadamy informację o wersji biblioteki, więc teoretycznie zawsze możemy odtworzyć model.
