### ISSUE TITLE
Laboratoria 3 - liver_disorders

### ISSUE THREAD

**Issue by agosiewska** [mini-pw/2019L-WarsztatyBadawcze#69]
Wygrywają najwyższe AUC i Accuracy.
Przewidujemy zmienną `selector`
Jedna osoba nie może wygrać obu :)

**Comment by Siemashko** [comment]
model_id: 8e4d9e45a4c1c8802d4b210c4a84cf3e
AUC: 0.8336134453781512
Acc: 0.8076923076923077
