### ISSUE TITLE
hashowanie

### ISSUE THREAD

**Issue by agosiewska** [mini-pw/2019L-WarsztatyBadawcze#99]
**caret**
list(formuła dane, model, parametry)
Wszystkie takie elementy listy powinny być dokładnie takie same, jak w funkcji `train`. 
Co oznacza, że model, to nazwa metody, a parametry to obiekt generowany przez `expand.grid`.
`list(drinks ~ ., liver, "ranger", expand.grid(mtry = 3, splitrule = "variance",  min.node.size = 5))`
UWAGA: 
jeżeli train przyjmuje dodatkowe parametry, np
`train(target ~ ., data ,"glm", tuneGrid, famliy = binomial)`
to hasha tworzymy z listy:
`list(target ~ ., data, "glm", tuneGrid, famliy = binomial)`
Czyli wszelkie dodatkowe parametry dodajemy *nazwane* na końcu listy, w kolejności alfabetycznej.

Jeśli nie podajemy parametrów (w przypadku modeli, które ich nie mają) zamiast parametrów wstawiamy `NULL`.
Lista nienazwana

**mlr**
w Task `id="task"`
list(task, learner)
lista nienazwana

**scikit-learn**
ok

**Comment by hubertbaniecki** [comment]
Zakładając, że w pliku code.R mamy takie measures to mi działa coś takiego: 
`
#code.R 
#:# audit
measures <- list("MSE" = MSE, "RMSE" = RMSE, "MAE" = MAE, "R2" = R2)
measures

#skrypt
nhash <- hash
pasteHash <- paste("audit_", hash, sep="")
id <- regr_rf$call$form[[2]]               
target <- as.character(regr_rf$call$form[[2]])    # target z formuły z train           
parameters <- regr_rf$bestTune                    # usunąć kwadratowe nawiasy w pliku
task_id <- paste(modelType, "_", id, sep = "")
`
